Version 0.2.0 beta
encode/orm pull request #64
Opened 2020-04-09 15:01 UTC by tomchristie

I'll expand this issue once there's more here to discuss.
For now just pushing out a pre-release to work against with https://github.com/encode/dashboard

2021-08-11 09:19 UTC, aminalaee commented
@tomchristie Is this going to be continued? I can work on it if that's the case.

2021-08-11 10:00 UTC, tomchristie commented
I'm not planning on putting time into it myself, no.

2021-09-16 12:19 UTC, aminalaee requested changes

2021-09-16 12:19 UTC, aminalaee commented on docs/relationships.md
> +class Album(orm.Model):
The name is wrong.

2021-09-17 05:55 UTC, aminalaee approved these changes

2021-09-17 06:19 UTC, merged