Implement order by
encode/orm pull request #70
Opened 2020-07-31 06:41 UTC by AndTheDaysGoBy

Fixed according to the discussion in https://github.com/encode/orm/pull/26, e.g. generating a new QuerySet via init, and implemented order by. A timestamp was also added the `User` model in the tests for the sake of variance of types while testing order by.

2020-07-31 06:42 UTC, AndTheDaysGoBy commented
Sorry if not proper etiquette with respect to the prior pull request; however, the previous PR had dormant for over a year.

2020-10-21 11:08 UTC, MightySCollins commented
This PR or the previous one should really be looked into. This is core ORM functionality...
Sadly this project seems quite inactive and other very useful PR's seem abandoned.

2021-02-14 19:59 UTC, AndTheDaysGoBy commented
Actually, this issue has returned to my spotlight when I was trying to use or implement something like django-chunkator, but that would require the ability to order_By. If only that was supported, django-chunkator may be able to be used as is, or, if not, easily be ported.

2021-08-21 07:48 UTC, aminalaee requested changes

2021-08-21 07:48 UTC, aminalaee commented on orm/models.py
> +            order_args=args,
Need to add order_by to exists, offset, limit

2021-08-24 12:40 UTC, aminalaee approved these changes

2021-08-24 12:43 UTC, merged